# Generated by Django 4.2.11 on 2025-04-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_alter_firefighters_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firefighters',
            name='station',
        ),
    ]
